// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: sound.proto

package sound

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sound_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_sound_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_sound_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sound_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_sound_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_sound_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type SoundRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sound []byte `protobuf:"bytes,1,opt,name=sound,proto3" json:"sound,omitempty"`
}

func (x *SoundRequest) Reset() {
	*x = SoundRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sound_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoundRequest) ProtoMessage() {}

func (x *SoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sound_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoundRequest.ProtoReflect.Descriptor instead.
func (*SoundRequest) Descriptor() ([]byte, []int) {
	return file_sound_proto_rawDescGZIP(), []int{2}
}

func (x *SoundRequest) GetSound() []byte {
	if x != nil {
		return x.Sound
	}
	return nil
}

type SoundResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alarm       bool    `protobuf:"varint,1,opt,name=alarm,proto3" json:"alarm,omitempty"`
	Res         string  `protobuf:"bytes,2,opt,name=res,proto3" json:"res,omitempty"`
	TaggingRate float32 `protobuf:"fixed32,3,opt,name=tagging_rate,json=taggingRate,proto3" json:"tagging_rate,omitempty"`
}

func (x *SoundResponse) Reset() {
	*x = SoundResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sound_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoundResponse) ProtoMessage() {}

func (x *SoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sound_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoundResponse.ProtoReflect.Descriptor instead.
func (*SoundResponse) Descriptor() ([]byte, []int) {
	return file_sound_proto_rawDescGZIP(), []int{3}
}

func (x *SoundResponse) GetAlarm() bool {
	if x != nil {
		return x.Alarm
	}
	return false
}

func (x *SoundResponse) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

func (x *SoundResponse) GetTaggingRate() float32 {
	if x != nil {
		return x.TaggingRate
	}
	return 0
}

var File_sound_proto protoreflect.FileDescriptor

var file_sound_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x6f, 0x75, 0x6e, 0x64, 0x22, 0x1a, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x22, 0x1a, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x24, 0x0a, 0x0c,
	0x53, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x6f, 0x75,
	0x6e, 0x64, 0x22, 0x5a, 0x0a, 0x0d, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74,
	0x61, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0b, 0x74, 0x61, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x32, 0x60,
	0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65,
	0x12, 0x13, 0x2e, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x53, 0x6f,
	0x75, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x0b, 0x2e, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x50,
	0x69, 0x6e, 0x67, 0x1a, 0x0b, 0x2e, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x50, 0x6f, 0x6e, 0x67,
	0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x2f, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sound_proto_rawDescOnce sync.Once
	file_sound_proto_rawDescData = file_sound_proto_rawDesc
)

func file_sound_proto_rawDescGZIP() []byte {
	file_sound_proto_rawDescOnce.Do(func() {
		file_sound_proto_rawDescData = protoimpl.X.CompressGZIP(file_sound_proto_rawDescData)
	})
	return file_sound_proto_rawDescData
}

var file_sound_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sound_proto_goTypes = []interface{}{
	(*Ping)(nil),          // 0: sound.Ping
	(*Pong)(nil),          // 1: sound.Pong
	(*SoundRequest)(nil),  // 2: sound.SoundRequest
	(*SoundResponse)(nil), // 3: sound.SoundResponse
}
var file_sound_proto_depIdxs = []int32{
	2, // 0: sound.File.Define:input_type -> sound.SoundRequest
	0, // 1: sound.File.Connect:input_type -> sound.Ping
	3, // 2: sound.File.Define:output_type -> sound.SoundResponse
	1, // 3: sound.File.Connect:output_type -> sound.Pong
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sound_proto_init() }
func file_sound_proto_init() {
	if File_sound_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sound_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sound_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sound_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoundRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sound_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoundResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sound_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sound_proto_goTypes,
		DependencyIndexes: file_sound_proto_depIdxs,
		MessageInfos:      file_sound_proto_msgTypes,
	}.Build()
	File_sound_proto = out.File
	file_sound_proto_rawDesc = nil
	file_sound_proto_goTypes = nil
	file_sound_proto_depIdxs = nil
}
